replicaCount: 1
fullnameOverride: roboshop-notification


image:
  repository: dummy/roboshop-notification
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8008
  targetPort: 8008

ingress:
  enabled: true
  host: notification

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: {}

global:
  env: dev
  ingressClass: traefik
  imagePullPolicy: IfNotPresent
  dbHosts:
    mysql: ""
    mongodb: ""
    valkey: ""
    rabbitmq: ""
