replicaCount: 1
fullnameOverride: roboshop-catalogue


image:
  repository: dummy/roboshop-catalogue
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8002
  targetPort: 8002

ingress:
  enabled: true
  host: catalogue

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: {}

global:
  env: dev
  ingressClass: traefik
  imagePullPolicy: IfNotPresent
  dbHosts:
    mysql: ""
    mongodb: ""
    valkey: ""
    rabbitmq: ""
