replicaCount: 1

image:
  repository: dummy/roboshop-cart
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8003
  targetPort: 8003

ingress:
  enabled: true
  host: cart

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: {}

global:
  env: dev
  ingressClass: traefik
  imagePullPolicy: IfNotPresent
  dbHosts:
    mysql: ""
    mongodb: ""
    valkey: ""
    rabbitmq: ""
