replicaCount: 1
fullnameOverride: roboshop-orders


image:
  repository: dummy/roboshop-orders
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8007
  targetPort: 8007

ingress:
  enabled: true
  host: orders

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: {}

global:
  env: dev
  ingressClass: traefik
  imagePullPolicy: IfNotPresent
  dbHosts:
    mysql: ""
    mongodb: ""
    valkey: ""
    rabbitmq: ""
