replicaCount: 1
fullnameOverride: roboshop-ratings


image:
  repository: dummy/roboshop-ratings
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8006
  targetPort: 8006

ingress:
  enabled: true
  host: ratings

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env: {}

global:
  env: dev
  ingressClass: traefik
  imagePullPolicy: IfNotPresent
  dbHosts:
    mysql: ""
    mongodb: ""
    valkey: ""
    rabbitmq: ""
